### ISSUE TITLE
Doesn't run on Win 7

### ISSUE THREAD

**Issue by wildeyes** [fgnass/node-dev#110]
cross posted from https://github.com/anatoo/gulper/issues/2#issuecomment-163549127.

```
> gulper

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Module._extensions..js (module.js:432:10)
    at Object.nodeDevHook [as .js] (C:\...\project\node_modules\node-dev\lib\hook.js:43:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\...\project\node_modules\node-dev\lib\wrap.js:58:1)
    at Module._compile (module.js:425:26)
[ERROR] 11:08:26 SyntaxError
```

what could it be?

**Comment by bjornstar** [comment]
Looks like a SyntaxError.
