### ISSUE TITLE
node-dev crashes child process

### ISSUE THREAD

**Issue by sr3d** [fgnass/node-dev#115]
After a random request, node-dev would crash on my machine (OSX Yosemite) with this error:

/usr/local/lib/node_modules/node-dev/lib/index.js:119
  var i = mod.lastIndexOf(n)
              ^

TypeError: mod.lastIndexOf is not a function
    at getPrefix (/usr/local/lib/node_modules/node-dev/lib/index.js:119:15)
    at getLevel (/usr/local/lib/node_modules/node-dev/lib/index.js:109:11)
    at /usr/local/lib/node_modules/node-dev/lib/index.js:76:44
    at ChildProcess.handleMessage (/usr/local/lib/node_modules/node-dev/lib/ipc.js:19:43)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

However, the web server is still accepting the request to the port.  I'd have to run a "killall node" and restart node-dev.

**Comment by lovell** [comment]
I had the same problem with modules loaded via `vm.runInNewContext` - setting the `vm` option to false "fixed" this.

I think the solution is to handle the situation where [module.filename](https://github.com/fgnass/node-dev/blob/master/lib/hook.js#L53) is an Object itself containing a `filename` attribute rather than assuming this will always be a String.

**Comment by koresar** [comment]
Was fixed in node-dev v3.1.1. Here is the discussion: https://github.com/fgnass/node-dev/issues/130#issuecomment-216333600

This issue can be safely closed.
