### ISSUE TITLE
Node 6 - TypeError: mod.lastIndexOf is not a function

### ISSUE THREAD

**Issue by Alex0007** [fgnass/node-dev#130]
```
node-dev index.js 

/home/alex/.nvm/versions/node/v6.0.0/lib/node_modules/node-dev/lib/index.js:120
  var i = mod.lastIndexOf(n);
              ^

TypeError: mod.lastIndexOf is not a function
    at getPrefix (/home/alex/.nvm/versions/node/v6.0.0/lib/node_modules/node-dev/lib/index.js:120:15)
    at getLevel (/home/alex/.nvm/versions/node/v6.0.0/lib/node_modules/node-dev/lib/index.js:110:11)
    at /home/alex/.nvm/versions/node/v6.0.0/lib/node_modules/node-dev/lib/index.js:77:45
    at ChildProcess.handleMessage (/home/alex/.nvm/versions/node/v6.0.0/lib/node_modules/node-dev/lib/ipc.js:19:43)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```

Node 6
OS: Linux

**Comment by fgnass** [comment]
Thank you! That's really strange. The tests pass on Travis CI under Node 6.0.0 – Would you mind quickly cloning the repo to see if `npm i && npm test` fails on your machine?

**Comment by Alex0007** [comment]
Tests are passed. 

Reproduce this error: https://github.com/Alex0007/node-dev-bug
Also i've checked Node 5 and error remains

**Comment by fgnass** [comment]
Thanks again! Fix published as part of v3.1.1.

**Comment by VietDucPhan** [comment]
The issue is still present in node 6.3

**Comment by fgnass** [comment]
Which version of node-dev are you using?

**Comment by VietDucPhan** [comment]
@fgnass I used 6.3.0 the last time i checked. but now when i check version or do node-dev.
it show 
```
module.js:442
    throw err;
    ^

Error: Cannot find module 'clone'
```

**Comment by swapnil-tnex** [comment]
Node - v6.11.1
'TypeError: o.file.lastIndexOf is not a function' getting same error. OS is windows 10

**Comment by codesorter2015** [comment]
function getFileExtension(filename) {
    return filename.slice((filename.lastIndexOf(".") - 1 >>> 0) + 2);
}

I'm getting the following errors:
(node:21156) UnhandledPromiseRejectionWarning: TypeError: filename.lastIndexOf is not a function
    at getFileExtension (F:\galaxy\app.js:227:37)

**Comment by leonsenqos** [comment]
I'm to getting this issue, using windows 10 system with node v8.11.4

(node:15316) UnhandledPromiseRejectionWarning: TypeError: files[0].lastIndexOf is not a function
    at Promise.all.then (D:\xxxx\xxxxx\xxxxxx.js:218:95)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
