### ISSUE TITLE
Doesn't work well with Node v7.0

### ISSUE THREAD

**Issue by leaves4j** [fgnass/node-dev#189]
```
Error: ENFILE: file table overflow, open '/.../node_modules/bluebird/js/release/filter.js'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Module._extensions..js (module.js:581:20)
    at Object.nodeDevHook [as .js] (/usr/local/lib/node_modules/node-dev/lib/hook.js:61:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at module.exports (/.../node_modules/bluebird/js/release/promise.js:747:1)
    at Object.<anonymous> (/.../node_modules/bluebird/js/release/bluebird.js:9:36)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.nodeDevHook [as .js] (/usr/local/lib/node_modules/node-dev/lib/hook.js:61:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

**Comment by jonathanong** [comment]
i'm seeing this all the time with node v6... very annoying

**Comment by alanjames1987** [comment]
I'm having the same problem:

OS X: 10.11.6
Node: 6.9.4

**Comment by qqilihq** [comment]
Experiencing the same problem which is a pity because I relly like the zero config idea of node-dev. Did you guy find a solution or switch to a different tool?

**Comment by fgnass** [comment]
Mac OS has a very low file descriptor limit by default. You can fix it like this:

```
# Increase the kernel's maxfiles limits
sudo sysctl -w kern.maxfiles=65536
sudo sysctl -w kern.maxfilesperproc=65536

# Persist settings across reboots
echo kern.maxfiles=65536 | sudo tee -a /etc/sysctl.conf
echo kern.maxfilesperproc=65536 | sudo tee -a /etc/sysctl.conf

# Raise the limit for your user
ulimit -n 65536 65536

# Add it to your shell's profile
echo "ulimit -n 65536 65536" >> $HOME/.bash_profile
````

BTW, watchman suggests to use even higher numbers:
https://facebook.github.io/watchman/docs/install.html#mac-os-file-descriptor-limits

They do the `ulimit` part themselves which is pretty convenient. This would make a nice addition to `node-dev`.

**Comment by qqilihq** [comment]
@fgnass Thank you, that sounds very promising! I'll give that a try and get back.

**Comment by bjornstar** [comment]
Node v7 and v6 are no longer supported. This doesn't seem to be a problem anymore.
