### ISSUE TITLE
node-dev with arguments

### ISSUE THREAD

**Issue by shabanovtg** [fgnass/node-dev#198]
`node-dev server.js -r api`

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'api'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at module.js:631:12
    at Array.forEach (native)
    at Function.Module._preloadModules (module.js:630:12)
    at preloadModules (bootstrap_node.js:323:38)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:467:3
```

When I use simple node `node server.js -r api` the server starts.

**Comment by muhfuhcaw** [comment]
node-dev inspect would be nice to have. :)

**Comment by alphashuro** [comment]
is inspect still not supported?

**Comment by ellipticaldoor** [comment]
Inspect is really useful, can't be supported?
