### ISSUE TITLE
node-dev crashes when attempting restart (permissions?)

### ISSUE THREAD

**Issue by bsarrazin** [fgnass/node-dev#199]
Here's the crash:
```zsh
$ node-dev app.js
Express app running on port 8080...
[INFO] 19:35:27 Restarting
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.exports.execFile (child_process.js:208:15)
    at Object.module.exports.fileCommand (/usr/local/lib/node_modules/node-dev/node_modules/node-notifier/lib/utils.js:53:13)
    at NotificationCenter.notify (/usr/local/lib/node_modules/node-dev/node_modules/node-notifier/notifiers/notificationcenter.js:66:11)
    at /usr/local/lib/node_modules/node-dev/lib/notify.js:16:16
    at FileWatcher.<anonymous> (/usr/local/lib/node_modules/node-dev/lib/index.js:36:5)
    at emitTwo (events.js:125:13)
    at FileWatcher.emit (events.js:213:7)
```

Node 8.4.0
NPM 5.4.0
Node installed through Hombrew on macOS 10.12.6

**Comment by bjornstar** [comment]
If this is still occurring with the latest version please re-open.
