### ISSUE TITLE
Node js 

### ISSUE THREAD

**Issue by swapnil-tnex** [fgnass/node-dev#204]
TypeError: o.file.lastIndexOf is not a function
    at resolve_book_type (D:\Projects\NodeJSProjects\*******.git\node_modules\xlsx\xlsx.js:18530:32)
    at Object.writeFileSync (D:\Projects\NodeJSProjects\******.git\node_modules\xlsx\xlsx.js:18538:2)
    at Timeout.sendWithdrawRequestViaMail [as _onTimeout] (D:/Projects/NodeJSProjects/*****/crons/SendWithDrawRequest.js:39:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

I am using xlsx npm for parsing xls, but I am getting the above error. Node version - v6.11.1 and OS - Windows.

**Comment by bjornstar** [comment]
This looks like it's related to the xlsx module. If you find it's an issue with node-dev directly please reopen with more details.
