### ISSUE TITLE
TypeError: val.lastIndexOf is not a function

### ISSUE THREAD

**Issue by nexgenkannan** [fgnass/node-dev#216]
Hi Team ,

Facing below issue in nodejs version v10.15.1
/home/kamal/ProjectGun/node_modules/gun/lib/store.js:51
			tmp = val.lastIndexOf('>');
			          ^

TypeError: val.lastIndexOf is not a function
    at each (/home/kamal/ProjectGun/node_modules/gun/lib/store.js:51:14)
    at /home/kamal/ProjectGun/node_modules/gun/lib/store.js:46:23
    at r (/home/kamal/ProjectGun/node_modules/gun/lib/radisk.js:49:14)
    at Object.next (/home/kamal/ProjectGun/node_modules/gun/lib/store.js:37:3)
    at Object.onto [as on] (/home/kamal/ProjectGun/node_modules/gun/gun.js:203:41)
    at Function.Gun.on.get (/home/kamal/ProjectGun/node_modules/gun/gun.js:845:10)
    at Object.root [as next] (/home/kamal/ProjectGun/node_modules/gun/gun.js:712:14)
    at Object.next (/home/kamal/ProjectGun/node_modules/gun/nts.js:18:20)
    at Object.security [as next] (/home/kamal/ProjectGun/node_modules/gun/sea.js:1135:23)
    at Object.onto [as on] (/home/kamal/ProjectGun/node_modules/gun/gun.js:203:41)

Please provide your comments on this issue

**Comment by nexgenkannan** [comment]
Updated to version v11.8.0 stable but still issue persists

**Comment by bjornstar** [comment]
This doesn't look like it's related to `node-dev`, you might try looking at the package that shows up in your stackTrace: https://www.npmjs.com/package/gun
