### ISSUE TITLE
Using -r esm broke with 6.0 release

### ISSUE THREAD

**Issue by daveisfera** [fgnass/node-dev#236]
When running this command: `node_modules/.bin/node-dev -r esm --inspect=0.0.0.0:9229 test_inspect.js`

I get this error:
```
/Users/dlj/projects/test_inspect/node_modules/resolve/lib/sync.js:91
    throw err;
    ^

Error: Cannot find module '--inspect=0.0.0.0:9229' from '/Users/dlj/projects/test_inspect'
    at resolveSync (/Users/dlj/projects/test_inspect/node_modules/resolve/lib/sync.js:89:15)
    at module.exports (/Users/dlj/projects/test_inspect/node_modules/node-dev/lib/resolve-main.js:4:10)
    at getConfig (/Users/dlj/projects/test_inspect/node_modules/node-dev/lib/cfg.js:31:16)
    at Object.<anonymous> (/Users/dlj/projects/test_inspect/node_modules/node-dev/lib/wrap.js:14:34)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1277:12) {
  code: 'MODULE_NOT_FOUND'
}
```

And unfortunately, using `NODE_OPTIONS` doesn't work (see #235)

**Comment by bjornstar** [comment]
It looks like an argument parsing issue, it works if the order is changed to:

`node_modules/.bin/node-dev --inspect=0.0.0.0:9229 -r esm test_inspect.js`

The argument parsing did change a bit in v6, let me see if I can fix it.
